### ISSUE TITLE
Expected Messages from Unit Tests Fail when Publishing

### ISSUE THREAD

**Issue by rich-hart** [Connexions/cnx-authoring#209]
There are now two possible messages that authoring can receive from publishing.  Either, 'Done/Success' or 'Waiting for moderation'.  Unit tests will need to be updated to reflect this change.

**Comment by pumazi** [comment]
I believe @karenc has this in here current pull request.

**Comment by rich-hart** [comment]
Here are some of the places where the failures are occurring. 
```python
======================================================================
FAIL: test_delete_after_publish (cnxauthoring.tests.test_functional.PublicationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-authoring/cnxauthoring/tests/test_functional.py", line 3444, in test_delete_after_publish
    self.assertEqual(publish['state'], 'Done/Success')
AssertionError: u'Waiting for moderation' != 'Done/Success'
 
======================================================================
FAIL: test_edit_after_publish (cnxauthoring.tests.test_functional.PublicationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-authoring/cnxauthoring/tests/test_functional.py", line 3375, in test_edit_after_publish
    self.assertEqual(publish['state'], 'Done/Success')
AssertionError: u'Waiting for moderation' != 'Done/Success'
 
======================================================================
FAIL: test_publish_after_error (cnxauthoring.tests.test_functional.PublicationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-authoring/cnxauthoring/tests/test_functional.py", line 3515, in test_publish_after_error
    self.assertEqual(publish['state'], 'Done/Success')
AssertionError: u'Waiting for moderation' != 'Done/Success'
 
======================================================================
FAIL: test_publish_binder (cnxauthoring.tests.test_functional.PublicationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-authoring/cnxauthoring/tests/test_functional.py", line 3181, in test_publish_binder
    self.assertEqual(response.json[u'state'], u'Done/Success')
AssertionError: u'Waiting for moderation' != u'Done/Success'
- Waiting for moderation
+ Done/Success
 
 
======================================================================
FAIL: test_publish_binder_w_printStyle (cnxauthoring.tests.test_functional.PublicationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-authoring/cnxauthoring/tests/test_functional.py", line 3258, in test_publish_binder_w_printStyle
    self.assertEqual(response.json[u'state'], u'Done/Success')
AssertionError: u'Waiting for moderation' != u'Done/Success'
- Waiting for moderation
+ Done/Success
 
 
======================================================================
FAIL: test_publish_derived_from_binder (cnxauthoring.tests.test_functional.PublicationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-authoring/cnxauthoring/tests/test_functional.py", line 3303, in test_publish_derived_from_binder
    self.assertEqual(publication_info['state'], 'Done/Success')
AssertionError: u'Waiting for moderation' != 'Done/Success'
 
======================================================================
FAIL: test_publish_derived_from_single_page (cnxauthoring.tests.test_functional.PublicationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-authoring/cnxauthoring/tests/test_functional.py", line 3123, in test_publish_derived_from_single_page
    self.assertEqual(publication_info['state'], 'Done/Success')
AssertionError: u'Waiting for moderation' != 'Done/Success'
 
======================================================================
FAIL: test_publish_single_pages (cnxauthoring.tests.test_functional.PublicationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-authoring/cnxauthoring/tests/test_functional.py", line 3083, in test_publish_single_pages
    self.assertEqual(response.json[u'state'], u'Done/Success')
AssertionError: u'Waiting for moderation' != u'Done/Success'
- Waiting for moderation
+ Done/Success
 
 
======================================================================
FAIL: test_publish_w_multiple_users (cnxauthoring.tests.test_functional.PublicationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/openstax/workspace/openstax_scripts/development/cnx-authoring/cnxauthoring/tests/test_functional.py", line 3581, in test_publish_w_multiple_users
    self.assertEqual(publish['state'], 'Done/Success')
AssertionError: u'Waiting for moderation' != 'Done/Success'
 
----------------------------------------------------------------------
Ran 156 tests in 22.632s
 
FAILED (failures=9)
```
