### ISSUE TITLE
Content with data- attribute is not editable

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx-authoring#234]
I created a module on legacydev which had a data: attribute. I published it and view it on dev.cnx.org. I then went to edit it on dev.cnx.org and I could not load anything into my workspace. The logs had this error:

>127.0.0.1 - - [04/Aug/2015:14:14:17 -0500] "GET /users/profile HTTP/1.0" 401 - "http://dev.cnx.org/workspace" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"
2015-08-04 14:14:17,366 ERROR [waitress][Dummy-3] Exception when serving /users/contents
Traceback (most recent call last):
  File "/opt/dev/local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/channel.py", line 337, in service
    task.service()
  File "/opt/dev/local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 173, in service
    self.execute()
  File "/opt/dev/local/lib/python2.7/site-packages/waitress-0.8.9-py2.7.egg/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid_translogger-0.1-py2.7.egg/pyramid_translogger/__init__.py", line 119, in tween
    response = handler(request)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/config/views.py", line 218, in wrapper
    response = view(context, request)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/opt/dev/local/lib/python2.7/site-packages/pyramid-1.5.1-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/opt/dev/local/lib/python2.7/site-packages/cnx_authoring-0.6.0-py2.7.egg/cnxauthoring/views.py", line 53, in wrapper
    return function(request, *args, **kwargs)
  File "/opt/dev/local/lib/python2.7/site-packages/cnx_authoring-0.6.0-py2.7.egg/cnxauthoring/views.py", line 61, in wrapper
    response = function(*args, **kwargs)
  File "/opt/dev/local/lib/python2.7/site-packages/cnx_authoring-0.6.0-py2.7.egg/cnxauthoring/views.py", line 157, in user_contents
    item = content.__json__()
  File "/opt/dev/local/lib/python2.7/site-packages/cnx_authoring-0.6.0-py2.7.egg/cnxauthoring/models.py", line 184, in __json__
    result['is_publishable'] = self.is_publishable
  File "/opt/dev/local/lib/python2.7/site-packages/cnx_authoring-0.6.0-py2.7.egg/cnxauthoring/models.py", line 199, in is_publishable
    return not bool(self.publication_blockers)
  File "/opt/dev/local/lib/python2.7/site-packages/cnx_authoring-0.6.0-py2.7.egg/cnxauthoring/models.py", line 194, in publication_blockers
    return utils.validate_for_publish(self)
  File "/opt/dev/local/lib/python2.7/site-packages/cnx_authoring-0.6.0-py2.7.egg/cnxauthoring/utils.py", line 688, in validate_for_publish
    blockers.extend(_validate_required_data(model))
  File "/opt/dev/local/lib/python2.7/site-packages/cnx_authoring-0.6.0-py2.7.egg/cnxauthoring/utils.py", line 663, in _validate_required_data
    tree = etree.parse(io.StringIO(content))
  File "lxml.etree.pyx", line 3299, in lxml.etree.parse (src/lxml/lxml.etree.c:72655)
  File "parser.pxi", line 1808, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:106460)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:106689)
  File "parser.pxi", line 1709, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:105390)
  File "parser.pxi", line 1047, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:99763)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:94543)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:96003)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:95050)
XMLSyntaxError: Namespace prefix data for test on p is not defined, line 5, column 18

devlegacy module - https://legacydev.cnx.org/content/m54559/1.1/?legacy=true
dev.cnx.org page - http://dev.cnx.org/contents/8b519e09-8cc5-4bc2-ac25-3f5b867266c6@1/data--test

**Comment by pumazi** [comment]
You've going to need to provide more info. What is the content that you posted/saved?

**Comment by edwoodward** [comment]
Links are added to original description.

**Comment by pumazi** [comment]
I'd guess something wasn't restarted. I'm seeing both the old and new data namespaces in the content.

**Comment by edwoodward** [comment]
This is fixed
